source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'HelloBoardy' do
  pod 'Alamofire'
	pod 'Boardy'
	pod 'TinyInjector'
	pod 'SiFUtilities'
  pod 'SDWebImage'
  pod 'ViewStateCore'
  
  pod "HelloAuth", :path => "submodules/hello-auth"
  pod "HelloAuthIO", :path => "submodules/hello-auth"

  pod "GHSearch", :path => "submodules/gh-search"
  pod "GHSearchIO", :path => "submodules/gh-search"

  pod "Home", :path => "submodules/home"
  pod "HomeIO", :path => "submodules/home"
end
